@startuml packages
set namespaceSeparator none
package "PGLController" as PGLController {
}
package "PGLJourney" as PGLJourney {
}
package "PGLMain" as PGLMain {
}
package "PGLModel" as PGLModel {
}
package "PGLServerAPI" as PGLServerAPI {
}
package "PGLZigbee2mqttClient" as PGLZigbee2mqttClient {
}
package "PGLZoneController" as PGLZoneController {
}
PGLController --> PGLModel
PGLController --> PGLZigbee2mqttClient
PGLController --> PGLZoneController
PGLMain --> PGLController
PGLMain --> PGLModel
PGLZigbee2mqttClient --> PGLModel
PGLZoneController --> PGLJourney
PGLZoneController --> PGLModel
PGLZoneController --> PGLServerAPI
@enduml
